add option to wait for document render
kohheepeace/mr-pdf pull request #36
Opened 2021-09-06 11:38 UTC by lidkxx

Our app documentation is around 140 pdf pages with a lot of images. During a pdf generation using mr-pdf script I would encounter two problems:

1. Some large images not being rendered fully.
2. Any images past ~40th page would not get rendered in the document at all.

Seems we just need a bit of a timeout to let the script glue all the html content it downloads from the docusaurus pages.

I've added `--waitForRender` option that takes a `number` value of ms in case anyone encounters a similar problem. (I am sure this won't be necessary for lightweight docs that don't have too many images).

This fixes #28

2021-09-18 15:37 UTC, juniorbotelho commented
Excellent contribution :D. I was even thinking of doing what you were doing.

2021-09-18 16:41 UTC, juniorbotelho commented
## 🐱‍💻 Fixing...

## Result:

![image-correct](https://user-images.githubusercontent.com/47013295/133895932-1eaba336-cb31-471f-b947-eafdb2665a53.png)

In your approach there were some bugs that I fixed. Try to make a new PR.

## 🚀 Correct approach

The problem can be fixed using the native **puppeteer** function called ```waitFor()```.

```typescript
if (waitForRender) {
  // Todo: remove this sentence
  // await new Promise((r) => setTimeout(r, waitFor));
  await page.goto(`${nextPageURL}`);
  console.log(chalk.green('Rendering...'));
  await page.waitFor(waitFor);
} else {
  // Go to the page specified by nextPageURL
  await page.goto(`${nextPageURL}`, {
    waitUntil: 'networkidle0',
    timeout: 0,
  });
}
```

![fix-it](https://user-images.githubusercontent.com/47013295/133895993-f7e64407-06e0-4dd3-87fb-2b757e5373f3.png)

Make the same changes as above and create a new PR.

2021-09-18 17:35 UTC, juniorbotelho commented
## 🐱‍💻 Fixing...

## Result:

![image-correct](https://user-images.githubusercontent.com/47013295/133895932-1eaba336-cb31-471f-b947-eafdb2665a53.png)

In your approach there were some bugs that I fixed. Try to make a new PR.

## 🚀 Correct approach

The problem can be fixed using the native **puppeteer** function called ```waitFor()```.

```typescript
if (waitForRender) {
  // Todo: remove this sentence
  // await new Promise((r) => setTimeout(r, waitFor));
  await page.goto(`${nextPageURL}`);
  console.log(chalk.green('Rendering...'));
  await page.waitFor(waitFor);
} else {
  // Go to the page specified by nextPageURL
  await page.goto(`${nextPageURL}`, {
    waitUntil: 'networkidle0',
    timeout: 0,
  });
}
```

![fix-it](https://user-images.githubusercontent.com/47013295/133895993-f7e64407-06e0-4dd3-87fb-2b757e5373f3.png)

Make the same changes as above and create a new PR.

2021-09-18 17:37 UTC, juniorbotelho requested changes
Fixing it with (see conversation):

```typescript
if (waitForRender) {
  // Todo: remove this sentence
  // await new Promise((r) => setTimeout(r, waitFor));
  await page.goto(`${nextPageURL}`);
  console.log(chalk.green('Rendering...'));
  await page.waitFor(waitFor);
} else {
  // Go to the page specified by nextPageURL
  await page.goto(`${nextPageURL}`, {
    waitUntil: 'networkidle0',
    timeout: 0,
  });
}
```

2021-09-20 07:55 UTC, lidkxx commented
Yeah, your solution is a bit more sophisticated. Thanks for looking at mine!  Amended in my last commit. 

I've left the `waitForRender` option as `number` still, or do you think it's better off as a `string`?

2021-09-20 09:53 UTC, juniorbotelho commented
I'm glad you liked my suggestions 😅.

About the ```waitForRender``` attribute typing by default it is a ```string```, this is how **commander** sets the values.

2021-09-20 10:05 UTC, juniorbotelho commented
I'm glad you liked my suggestions 😅.

About the waitForRender attribute typing by default it is a string, this is how commander sets the values.

2021-12-30 19:07 UTC, humphd commented
Would love to see this get merged, as we're running into problems with images not rendering.

2021-12-30 19:13 UTC, juniorbotelho commented
@humphd I'll clone the project and I'll send you the link with it working.

2022-02-04 23:16 UTC, merged

2022-02-04 23:17 UTC, kohheepeace commented
@lidkxx  super thanks for your PR, and sorry for my late response.